#!/usr/bin/env python3
"""Diff the map-extracted series files against the GTFS-derived ones.

Produces a markdown report for hand review: series present in only one
source, per-serie stop-set differences, and the map-only editorial
information (exceptions). Combined map ids like 700/800 are matched against
the union of the GTFS parts.

Usage:
    uv run scripts/diff_map_gtfs.py > "research/2026-07-12 map-vs-gtfs-diff.md"
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"

PART_RE = re.compile(r"[0-9]{3,6}|R[SEB][0-9]{1,3}")


def load(path):
    if not path.exists():
        return None
    return {s["id"]: s for s in json.loads(path.read_text())["series"]}


def stops_of(s):
    return set(st for r in s["routes"] for st in r["stops"])


def parts_of(map_id):
    cleaned = re.sub(r"\([^)]*\)", "", map_id)
    return PART_RE.findall(cleaned) or [map_id]


def main():
    print("# Map versus GTFS discrepancy report")
    print()
    print("Generated by scripts/diff_map_gtfs.py. Map extraction is the editorial")
    print("truth (spits-only stops, direction markers, combined labels); GTFS is")
    print("the factual per-trip truth. Review disagreements by hand.")
    for page in (1, 2, 3, 4):
        map_series = load(DATA / f"page{page}.series.json")
        gtfs_series = load(DATA / "gtfs" / f"page{page}.series.json")
        print(f"\n## Page {page}")
        if map_series is None:
            print("\nMap extraction not landed yet, skipped.")
            continue
        if gtfs_series is None:
            print("\nGTFS file missing, skipped.")
            continue

        claimed_gtfs = set()
        shared = []
        map_only = []
        for mid, ms in map_series.items():
            gparts = [p for p in parts_of(mid) if p in gtfs_series]
            if gparts:
                claimed_gtfs.update(gparts)
                shared.append((mid, ms, gparts))
            else:
                map_only.append(mid)
        gtfs_only = sorted(set(gtfs_series) - claimed_gtfs)

        print(f"\nSeries: {len(map_series)} on the map, {len(gtfs_series)} in GTFS, "
              f"{len(shared)} matched, {len(map_only)} map-only, {len(gtfs_only)} GTFS-only.")
        if map_only:
            print(f"\nMap-only series (no GTFS counterpart): {', '.join(sorted(map_only))}")
        if gtfs_only:
            print(f"\nGTFS-only series (not printed on the map): {', '.join(gtfs_only)}")

        diffs = []
        for mid, ms, gparts in shared:
            mstops = stops_of(ms)
            gstops = set()
            for p in gparts:
                gstops |= stops_of(gtfs_series[p])
            only_map = sorted(mstops - gstops)
            only_gtfs = sorted(gstops - mstops)
            if only_map or only_gtfs:
                diffs.append((mid, only_map, only_gtfs))
        if diffs:
            print(f"\n### Stop-set disagreements ({len(diffs)} series)")
            for mid, om, og in sorted(diffs):
                print(f"\n- serie {mid}:")
                if om:
                    print(f"  - map heeft, GTFS niet: {', '.join(om)}")
                if og:
                    print(f"  - GTFS heeft, kaart niet: {', '.join(og)}")
        else:
            print("\nNo stop-set disagreements.")

        exc = [(mid, e) for mid, ms in sorted(map_series.items())
               for e in ms.get("exceptions", [])]
        if exc:
            print(f"\n### Map-only editorial information ({len(exc)} exceptions)")
            for mid, e in exc:
                st = f" [{e['station']}]" if e.get("station") else ""
                print(f"- {mid} ({e['type']}{st}): {e['note']}")

        low = [mid for mid, ms in sorted(map_series.items())
               if ms.get("confidence") != "high"]
        if low:
            print(f"\nNon-high confidence map series to eyeball: {', '.join(low)}")


if __name__ == "__main__":
    main()
